### PR TITLE
Made it possible to add icons to menu items on Mac

### PR DESCRIPTION
**Pull request by jefvel**

### CODE REVIEW

**Comment by joesis** [comment]
@jefvel Thanks. Do you mind to add a demo of `SetIcon` to the example and udpate README.md to mention that it's only available on macOS?

**Comment by jefvel** [comment]
@joesis Added info to readme and example.

**Comment by joesis** [comment]
Thanks @jefvel! LGTM. I still have issue on my side running the example (the systray doesn't show up at all, even with the master branch) but will merge as soon as I figuring it out.

**Comment by jefvel** [comment]
@joesis Does it show any errors?

**Comment by joesis** [comment]
It turns out that there's simply no enough room for the systray to be shown. Merging!

**Comment by jefvel** [comment]
Ah, alright 👍 Nice!

**Pull request merged**
