### PR TITLE
Intial work on NSMenuItem seperatorItem

### PR DESCRIPTION
**Pull request by xor-gate**
Work in progress to support separator items (only OSX for now)

Fixes partial #9 but not for windows...

### CODE REVIEW

**Comment by fffw** [comment]
Looks good. Thanks @xor-gate ! Could you update README.md as a new OSX-only feature?

**Comment by xor-gate** [comment]
Probably we should implement seperatorItem dummy-stubs for GTK and windows before this is actually useable. I'm not 100% happy how systray interfaces with the native implementions, but yeah thats life :_). Because I had to change the C-api. 

What do you think to first implement dummy-stubs and then update the README?

**Comment by fffw** [comment]
Sounds good @xor-gate.

**Comment by xor-gate** [comment]
I switched from golang-wrapped systray to native OSX systray written in Objective-C where I can use now all OSX primitives. I would like some help to implement the stubs for linux and windows if you want to merge this.

**Comment by fffw** [comment]
Yeah, it merely implemented the minimum cross-platform features Lantern project requires and didn't keep extendability in mind. I can integrate your changes later when a time slot is available. Thanks!

**Comment by martinlindhe** [comment]
Gave this a test as i needed it. It works fine for macOS. However it breaks compilation on linux (Ubuntu 17.04) like this:

```
# github.com/getlantern/systray
../../getlantern/systray/systray_linux.c: In function ‘nativeLoop’:
../../getlantern/systray/systray_linux.c:37:2: warning: ‘return’ with no value, in function returning non-void
  return;
  ^~~~~~
../../getlantern/systray/systray_linux.c:27:5: note: declared here
 int nativeLoop(void) {
     ^~~~~~~~~~
../../getlantern/systray/systray_linux.c: At top level:
../../getlantern/systray/systray_linux.c:143:6: error: conflicting types for ‘add_or_update_menu_item’
 void add_or_update_menu_item(int menu_id, char* title, char* tooltip, short disabled, short checked) {
      ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../getlantern/systray/systray_linux.c:6:0:
../../getlantern/systray/systray.h:8:6: note: previous declaration of ‘add_or_update_menu_item’ was here
 void add_or_update_menu_item(int menuId, short separator, char* title, char* tooltip, short disabled, short checked);
      ^~~~~~~~~~~~~~~~~~~~~~~
vm@vm:~/dev/go/src/github.com/martinlindhe/timer$ 
```

**Comment by xor-gate** [comment]
I'm not supporting this PR anymore. I have moved to my own native Objective-C implementation.

**Pull request closed without merging**
