### PR TITLE
Syscalls instead of custom DLLs

### LINKED ISSUE #3: Failed to load systray.dll (not a valid Win32 application)
Running main.go using go1.4.2 windows/amd64 from the example folder, on a Windows 8.1 machine:

```
panic: Failed to load C:\Users\dozn\AppData\Roaming/systray/systray.dll: %1 is not a valid Win32 application.

goroutine 1 [running, locked to thread]:
syscall.(*LazyProc).mustFind(0xc082009fb0)
        c:/go/src/syscall/dll_windows.go:259 +0x6f
syscall.(*LazyProc).Call(0xc082009fb0, 0xc082021f20, 0x2, 0x2, 0x0, 0xc0820023a0, 0x0, 0x0)
        c:/go/src/syscall/dll_windows.go:278 +0x44
github.com/getlantern/systray.nativeLoop()
        I:/Programming/Go/src/github.com/getlantern/systray/systray_windows.go:47 +0xea
github.com/getlantern/systray.Run(0x5696e8)
        I:/Programming/Go/src/github.com/getlantern/systray/systray.go:56 +0x9f
main.main()
        I:/Programming/Go/src/github.com/getlantern/systray/example/main.go:12 +0x31

goroutine 2 [runnable]:
runtime.forcegchelper()
        c:/go/src/runtime/proc.go:90
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        c:/go/src/runtime/mgc0.go:82
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        c:/go/src/runtime/malloc.go:712
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
github.com/getlantern/systray.func┬╖001()
        I:/Programming/Go/src/github.com/getlantern/systray/systray.go:51
created by github.com/getlantern/systray.Run
        I:/Programming/Go/src/github.com/getlantern/systray/systray.go:54 +0x98
exit status 2
```

I thought the file path looked funky, but even after correcting the path.Joins with filepath.Joins (which turns the "/" into "\" in the file path), I received the exact same error message. The DLL file does in fact exist in that directory.

Any ideas?

### LINKED ISSUE #18: Clean up dlls after on systray.Quit()
Hello.
I wanted to ask if it would be possible to delte the dlls in appdata when you run systray.Quit()
i had this code in the systray.Quit function before but it didn't work because for some reason the files were still in use.

```
    err := os.RemoveAll(dllDir)
    if err != nil {
        log.Debugf("Unable to delete temporary dll directory %v: %v", err)
    }
```

### LINKED ISSUE #22: Run without .dll
Why .dll is needed? It seems possible to avoid using it or `cgo`.

1. https://github.com/lxn/walk/issues/68 - win GUI toolkit that compiles without `cgo`
2. https://gist.github.com/nathan-osman/18c2e227ad00a223b61c0b3c16d452c3 - WinAPI access from Go
3. https://news.ycombinator.com/item?id=11962359 - thread with links above

### PR DESCRIPTION
**Pull request by amkulikov**
`systray_windows.go` is based on `systray.cpp` and has few improvements:
* Catches WM_TASKBARCREATED (explorer.exe started) message and redraws icon;
* SetIcon calculates md5 and adds it to filename. Tempfile will be reused if available;
* Handles of loaded images (recieved from LoadImage) are stored to map and reused.

This PR resolves #3, resolves #18, resolves #22 and partially #42.

### CODE REVIEW

**Comment by anjannath** [comment]
Tested the PR works as expected. @amkulikov Good job using syscalls, now we can further extend the libraries functionality with things like submenu, etc. #49

**Comment by anjannath** [comment]
@joesis PTAL, this will be very helpful towards extending the library, can you please merge this.

**Comment by joesis** [comment]
Sorry for the late @amkulikov @anjannath . Great effort and lots of improvements!

When I `GOOS=windows go build` the example on macOS, I got this:
```
# github.com/getlantern/systray/example
github.com/getlantern/systray.(*winTray).initInstance: relocation target golang.org/x/sys/windows.NewCallback not defined
github.com/getlantern/systray.(*winTray).initInstance: undefined: "golang.org/x/sys/windows.NewCallback"
```
I'm not sure if it's possible to write it in a way to cross build Windows on macOS/Linux, but it's critical for us to be able to do so. Our dev environment is mostly macOS. To build Linux binaries it's convenient to launch a Docker container, but launching a Windows VM doesn't seem to be an option.

**Comment by amkulikov** [comment]
@joesis please try 
`go get -u golang.org/x/sys/windows`
I think you have old version with bug  https://go-review.googlesource.com/c/sys/+/63250

**Comment by joesis** [comment]
Thanks @amkulikov! Code LGTM. Cross-built example works, so does the Lantern binary using it.

It opens the door to more features and improvements. @oxtoacart how do you think about this change?

**Comment by oxtoacart** [comment]
This is cool! I'm going to merge this into a branch so I can start trying it with Lantern.

**Comment by oxtoacart** [comment]
@joesis @amkulikov Working great for me too, going to merge to master. Thanks @amkulikov!

**Comment by anjannath** [comment]
@amkulikov I see you have other patches that are not part of this repo, please do consider sending all those patches also here, Thanks :smile: !!  

I have added code to create submenus and add bitmap menu item for windows, i am going to start implementing the same for macOS and Linux. Will send a PR once these implementations are done, and have cleaned up the code!

Thanks @oxtoacart and @joesis for merging this.

**Comment by myleshorton** [comment]
Sounds great @anjannath

**Pull request merged**
